version: '3.3'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    image: postgres:12.4

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env
  web:
    image: kucjlota/foodgram:v1
    volumes:
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    restart: always

    depends_on:
      - db
    env_file:
      - ./.env
    expose:
      - 8000

  nginx:
    image: nginx:1.19.6
    restart: unless-stopped
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_volume:/code/static/
      - ./media_volume:/code/media/
    ports: 
      - 80:80
    
    depends_on: 
      - web
